### ISSUE TITLE
WWC-Toolset/WWC CO2 capture code-Install

### ISSUE THREAD

**Issue by diyaguna** [CCSI-Toolset/WWC#2]
Hello,

Currently I am working on MEA based CO2 capture using OpenFOAM, I found your WWC-Toolset for CO2 capture study. But I could not able to install, Even I followed your instruction in manual. is it possible to get updated toolset or any recent update toolset.

**Comment by ksbeattie** [comment]
@diyaguna, can you provide more details on the installation? What OS you are on, the exact steps you took, what happened after each of those steps, what you expected to happen?  The more details, the better.

**Comment by ksbeattie** [comment]
@diyaguna, I'm closing this issue for now, if you still have questions, and more details so we can better help, feel free to re-open this issue.
